version: '3.3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: application-security
    environment: 
      - MONGO_URL=mongodb://mongodb
    volumes:
      - ./config:/app/config
    ports:
      - 8080:8080
    depends_on:
      - mongodb
